name: cholan
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=10.2
  - elasticsearch=7.16.2
  - ipython=7.29.0
  - natsort=7.0.1
  - nltk=3.6.5
  - matplotlib=3.5.1
  - numpy=1.19.2
  - pandas=1.3.5
  - python=3.7
  - pytorch=1.10.1
  - scikit-learn=1.0.1
  - seaborn=0.11.2
  - transformers=4.15.0